( Large letter F )
: STAR 42 EMIT ;
( : STARS   0 DO  STAR  LOOP ; )
: 5STARS STAR STAR STAR STAR STAR ;
: MARGIN  CR 30 SPACES ;
: BLIP MARGIN STAR ;
: BAR  MARGIN 5STARS ;
: F    BAR BLIP BAR BLIP BLIP CR ;
F
